# Generated by Django 4.1.3 on 2023-11-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher_alter_book_gambar_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
