# Generated by Django 4.1.3 on 2023-11-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('noRekamMedis', models.IntegerField(primary_key=True, serialize=False)),
                ('namaPasien', models.CharField(max_length=250)),
                ('alamat', models.CharField(max_length=250)),
                ('tanggalLahir', models.DateField()),
                ('dokter', models.IntegerField()),
                ('departemen', models.CharField(max_length=250)),
                ('diagnosa', models.TextField(max_length=250)),
                ('tindakan', models.TextField(max_length=250)),
            ],
        ),
    ]
