# Generated by Django 4.1.3 on 2023-11-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasiData', '0003_alter_datapasien_dokter'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasien',
            name='jenisKelamin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
